- Site:
    pages: 
      - title: Card.Batt
        file: issues
        desc: collections of photos ive taken in albums w/ music!
      - title: Photos
        file: photos
        desc: all the photos ive uploaded to this site
      - title: Updates
        file: updates
        desc: site updates and short posts
      - title: Projects
        file: projects
        desc: things i am working on - will update pages as i go
      - title: Links
        file: links
        desc: incl. middle english libraries and mobile phone museums
      - title: About
        file: about
        desc: sign my guestbook!
      
    name: it IS a crouton



#<------UPDATES------>
- Update:
    title: tidying up more
    date: 2026-02-20 12:53
    content: thinking that maybs the style for the card.batt section should be completely different. a subsite if u will... also need a favicon
    
- Update:
    title: added stuff about my site generator
    date: 2026-02-17 21:25
    content: in the projects section there is now stuff about the static site generator i built for this site. a little shoddy.

- Update:
    title: added links! check them out
    date: 2026-02-17 21:25
    content: added links to the links page -> wanna categorise them and add more but will do for now :)
    
- Update:
    title: finally added more stuff! project section
    date: 2026-02-17 14:56
    content: have added a new section for projects but nothing there rn. also still need to add links. and trasnfer a new card.batt post to website

- Update:
    title: having second about design... no personality
    date: 2026-01-09 21:43
    content: okay upon further reflection i need a site w/ more personality... idk if i try and make this one less clinical or just yk from scratch. need little sections for all my multitudes yk...

- Update:
    title: new site
    date: 2026-01-07 15:00
    content: i think i have an operational website... still not sure about the theme but it is up and running. maybe lacking a litle personality... i'll get there fr



#<------ISSUES------>
- Issue:
    title: nzny
    slug: nzny
    date: 2025-01-07 16:00
    desc: first webpost!
    audio: https://od.lk/s/MjlfNTg0MTM0OTNf/when_things_come_falling_down.mp3
    content: |
        \i{DSCF0228.JPG}
        \i{DSCF0025.JPG}
        \i{DSCF0068.JPG}
        \i{DSCF0250.JPG}
        \i{DSCF0323.JPG}
        \i{DSCF0187.JPG}
        \i{DSCF0898.JPG}
        \i{DSCF0889.JPG}
        \i{DSCF0242.JPG}
        \i{DSCF0702.JPG}
        \i{DSCF0343.JPG}
        \i{DSCF0209.JPG}
        \i{DSCF0318.JPG}
        \i{DSCF0974.JPG}
        the horse didnt rlly like me and nor did the starfish. i like them both though. and the building.
    thumbnail: photos/DSCF0228.JPG



#<-----PROJECTS------>
- Project:
    title: internetsupermagazine
    slug: internetsupermagazine
    desc: printable web collation
    content: |
        rn this is empty but check it out here -> \l{https://github.com/Tulk6/internetsupermagazine}

- Project:
    title: ncities5
    slug: ncities5
    desc: fifth (current) version of this site
    content: >
        19/02/26
        Here is the github -> \l{https://github.com/Tulk6/ncities5}

        
        Site is made using a static site generator I am writing, which uses the mustache templating 
        engine and a big YAML file with all the posts and links and sections and this very text I'm writing rn!


        A python script goes through a source directory which contains a) this YAML file, and b) the templates and then provides the 
        dict that it gets from reading the YAML file to the templates which do all the rest. Also does stuff to make a seperate file for each project
        and article and so on. It then puts all the compiled HTML into another folder along with CSS ive written and the fonts and images and so on, 
        and then another program I've written to interface with the neocities API uploads all the files, and syncs the local folder to the server 
        one. Hopefully 🤞🤞 this all means that although i already rlly wanna change the design and layout and so on of my site, doing so should only
        rlly mean rewriting the templates and the css, and not having to rewrite all the content itself. which I thought would be nice.


        Still need to add some things (e.g. smth to resize photos that I upload so they take up less room &c &c but that can wait). 


        Also rlly recommend mustache. Very fun.


        Okee buh bye.

        
#<-----LINKS------>
- Link:
    title: MediaRemix
    url: https://www.pentacom.jp/soft/
    desc: random software incl. paper computer which is very very very cool

- Link:
    title: icon basics
    url: https://www.pentacom.jp/icon/index.html
    desc: cool icons and site

- Link:
    title: Colour Problems
    url: https://colorproblems.art/
    desc: a web recreation of a 1902 colour theory book analyser thing...

- Links:
    title: Wiby
    url: https://wiby.me/
    desc: awesome search engine for classic web

- Link:
    title: Werner's Nomenclature of Colours
    url: https://www.c82.net/werner/#preface
    desc: similar but this time all colour names - v cool

- Link: 
    title: Half Life 2 Shading
    url: https://www.c82.net/werner/#preface
    desc: a valve slideshow about half life two's shading

- Link:
    title: bibliotheca Augustana
    url: https://www.hs-augsburg.de/~harsch/augustana.html
    desc: a library of texts in ancient greek and latin and french and english and more

- Links:
    title: Mobile Phone Museum
    url: https://www.mobilephonemuseum.com/catalogue
    desc: mobile phone museum
    
- Link:
    title: YourSmileys
    url: https://yoursmiles.org/
    desc: lots of animated emoticons

- Link:
    title: Tiny Tool Directory
    url: https://tinytools.directory/
    desc: a whole bunch of tools for a whole bunch of things

- Link:
    title: Texture Town
    url: https://textures.neocities.org/
    desc: cool textures

- Link:
    title: Open RSS
    url: https://openrss.org/
    desc: lots of rss tools - feeds for diff sites

- Link:
    title: notes from earth
    url: https://notesfromearth.neocities.org/
    desc: cool site

- Links: 
    title: Marginalia
    url: https://marginalia-search.com/
    desc: like wiby but broader

- Links:
    title: Panlexicon
    url: https://panlexicon.com/
    desc: like a thesaurus but cooler

- Link:
    title: Letters from the past
    url: https://victorianweb.org/previctorian/letters/lettersov.html
    desc: letters from the past

- Link:
    title: David Byrne radio
    url: https://www.mixcloud.com/Todomundo/
    desc: david byrne posts playlists more or less weekly v cool

- Link:
    title: Public Domain Review
    url: https://publicdomainreview.org/
    desc: online journal focused on work in public domain

- Link:
    title: National Geographic issues from the 90s
    url: https://archive.org/details/1990-ngs-pdf/295EC01A.JPG
    desc: what the title says

- Link:
    title: Whole Earth Index
    url: https://wholeearth.info/
    desc: archive of the whole earth catalogue and others very interesting articles

- Link:
    title: Archive Fashion
    url: https://www.archivepdf.net/
    desc: i know nothing about high fashion but the magazines r cool

- Link:
    title: Standard EBooks
    url: https://standardebooks.org/
    desc: public domain ebooks very nicely formatted

- Links:
    title: METS
    url: https://metseditions.org/
    desc: middle english texts
