#need to add
#    currently reading watching etc
#    fix media log -> dates, loved, filtering
#    ------improve about page
#    find room for more colour
#    switch to css grid??
#    -----add a welcome section
#    add links to profiles
#    theme overhaul...

#    add custom gif emojis in my markup lang

- Site:
    pages: 
      - title: Card.Batt
        file: issues
        desc: collections of photos ive taken in albums w/ music!
      - title: Updates
        file: updates
        desc: site updates and short posts
      - title: Projects
        file: projects
        desc: things i am working on - will update pages as i go
      - title: Links
        file: links
        desc: incl. middle english libraries and mobile phone museums
      - title: Media
        file: media
        desc: my media log - a little incomplete
      - title: Photos
        file: photos
        desc: all the photos ive uploaded to this site
      - title: About
        file: about
        desc: sign my guestbook!
      
    name: it IS a crouton


#<------UPDATES------>
- Update:
    title: my site is now fish themed
    date: 2026-03-02 16:30
    content: ive made my site fish themed... idk if it will stay this way
    
- Update:
    title: media page and o week
    date: 2026-02-25 18:58
    content: have made the media bit more functional and had my uni o-week!
    
- Update:
    title: new homepage slightly
    date: 2026-02-23 17:10
    content: have gotten rid of h2s on homepage and made all the links blue... let me know if its an improvement
    
- Update:
    title: new photos
    date: 2026-02-23 11:43
    content: new photos. Dreading having to tutor people tomorrow... Not dreading doing uni orientation! D= =D
    
- Update:
    title: tidying up more
    date: 2026-02-20 12:53
    content: thinking that maybs the style for the card.batt section should be completely different. a subsite if u will... also need a favicon
    
- Update:
    title: added stuff about my site generator
    date: 2026-02-17 21:25
    content: in the projects section there is now stuff about the static site generator i built for this site. a little shoddy.

- Update:
    title: added links! check them out
    date: 2026-02-17 21:25
    content: added links to the links page -> wanna categorise them and add more but will do for now :)
    
- Update:

    title: finally added more stuff! project section
    date: 2026-02-17 14:56
    content: have added a new section for projects but nothing there rn. also still need to add links. and trasnfer a new card.batt post to website

- Update:
    title: having second about design... no personality
    date: 2026-01-09 21:43
    content: okay upon further reflection i need a site w/ more personality... idk if i try and make this one less clinical or just yk from scratch. need little sections for all my multitudes yk...

- Update:
    title: new site
    date: 2026-01-07 15:00
    content: i think i have an operational website... still not sure about the theme but it is up and running. maybe lacking a litle personality... i'll get there fr



#<------ISSUES------>
- Issue:
    title: preun
    slug: preun
    date: 2025-02-23 09:26
    desc: got new cameras..
    audio: https://od.lk/s/MjlfNTk1ODE2Mzdf/peaches.mp3
    audio_title: peaches.mp3
    #peaches
    richcontent: |
        \i{100_6206.jpg}
        \i{100_6126.jpg}
        \i{100_6363.jpg}
        \i{DSCF0446.jpg}
        \i{DSCF0435.jpg}
        \i{DSCF0510.jpg}
        \i{DSCF0458.jpg}
        \i{100_6255.jpg}
        \i{100_6377.jpg}
        \i{DSCF0455.jpg}
        \i{DSCF0513.jpg}
        \i{100_6138.jpg}
        \i{100_6214.jpg}
        \i{100_6206.jpg}
        AAAAH what was that... i have new cameras i hope that doesnt change things between you and me (the date is 2006 bcos it doesn't up go up to 2026) also check out my radical website (a little meta cos ur looking at it rn) + these ties remind me of mitch and cam + i made a rlly nice berry pie.... dam fine. ahh there it is again.
    thumbnail: photos/100_6206.jpg
    
- Issue:
    title: nzny
    slug: nzny
    date: 2025-01-07 16:00
    desc: first webpost!
    audio: https://od.lk/s/MjlfNTg0MTM0OTNf/when_things_come_falling_down.mp3
    audio_title: when_things_come_falling_down.mp3
    richcontent: |
        \i{DSCF0228.jpg}
        \i{DSCF0025.jpg}
        \i{DSCF0068.jpg}
        \i{DSCF0250.jpg}
        \i{DSCF0323.jpg}
        \i{DSCF0187.jpg}
        \i{DSCF0898.jpg}
        \i{DSCF0889.jpg}
        \i{DSCF0242.jpg}
        \i{DSCF0702.jpg}
        \i{DSCF0343.jpg}
        \i{DSCF0209.jpg}
        \i{DSCF0974.jpg}
        the horse didnt rlly like me and nor did the starfish. i like them both though. and the building.
    thumbnail: photos/DSCF0228.jpg



#<-----PROJECTS------>
- Project:
    title: my font
    slug: myfont
    desc: a sans-serif pixel font i made
    richcontent: |
        made a font.
        
- Project:
    title: internetsupermagazine
    slug: internetsupermagazine
    desc: printable web collation
    richcontent: |
        rn this is empty but check it out here -> \l{https://github.com/Tulk6/internetsupermagazine}

- Project:
    title: ncities5
    slug: ncities5
    desc: fifth (current) version of this site
    richcontent: >
        19/02/26
        Here is the github -> \l{https://github.com/Tulk6/ncities5}

        
        Site is made using a static site generator I am writing, which uses the mustache templating 
        engine and a big YAML file with all the posts and links and sections and this very text I'm writing rn!


        A python script goes through a source directory which contains a) this YAML file, and b) the templates and then provides the 
        dict that it gets from reading the YAML file to the templates which do all the rest. Also does stuff to make a seperate file for each project
        and article and so on. It then puts all the compiled HTML into another folder along with CSS ive written and the fonts and images and so on, 
        and then another program I've written to interface with the neocities API uploads all the files, and syncs the local folder to the server 
        one. Hopefully 🤞🤞 this all means that although i already rlly wanna change the design and layout and so on of my site, doing so should only
        rlly mean rewriting the templates and the css, and not having to rewrite all the content itself. which I thought would be nice.


        Still need to add some things (e.g. smth to resize photos that I upload so they take up less room &c &c but that can wait). 


        Also rlly recommend mustache. Very fun.


        Okee buh bye.

        
#<-----LINKS------>
- Link:
    title: MediaRemix
    url: https://www.pentacom.jp/soft/
    desc: random software incl. paper computer which is very very very cool

- Link:
    title: icon basics
    url: https://www.pentacom.jp/icon/index.html
    desc: cool icons and site

- Link:
    title: Colour Problems
    url: https://colorproblems.art/
    desc: a web recreation of a 1902 colour theory book analyser thing...

- Links:
    title: Wiby
    url: https://wiby.me/
    desc: awesome search engine for classic web

- Link:
    title: Werner's Nomenclature of Colours
    url: https://www.c82.net/werner/#preface
    desc: similar but this time all colour names - v cool

- Link: 
    title: Half Life 2 Shading
    url: https://valvearchive.com/Presentations/GDC%202004/d3dtutorial10_half-life2_shading.pdf
    desc: a valve slideshow about half life two's shading

- Link:
    title: bibliotheca Augustana
    url: https://www.hs-augsburg.de/~harsch/augustana.html
    desc: a library of texts in ancient greek and latin and french and english and more

- Links:
    title: Mobile Phone Museum
    url: https://www.mobilephonemuseum.com/catalogue
    desc: mobile phone museum
    
- Link:
    title: YourSmileys
    url: https://yoursmiles.org/
    desc: lots of animated emoticons

- Link:
    title: Tiny Tool Directory
    url: https://tinytools.directory/
    desc: a whole bunch of tools for a whole bunch of things

- Link:
    title: Texture Town
    url: https://textures.neocities.org/
    desc: cool textures

- Link:
    title: Open RSS
    url: https://openrss.org/
    desc: lots of rss tools - feeds for diff sites

- Link:
    title: notes from earth
    url: https://notesfromearth.neocities.org/
    desc: cool site

- Links: 
    title: Marginalia
    url: https://marginalia-search.com/
    desc: like wiby but broader

- Links:
    title: Panlexicon
    url: https://panlexicon.com/
    desc: like a thesaurus but cooler

- Link:
    title: Letters from the past
    url: https://victorianweb.org/previctorian/letters/lettersov.html
    desc: letters from the past

- Link:
    title: David Byrne radio
    url: https://www.mixcloud.com/Todomundo/
    desc: david byrne posts playlists more or less weekly v cool

- Link:
    title: Public Domain Review
    url: https://publicdomainreview.org/
    desc: online journal focused on work in public domain

- Link:
    title: National Geographic issues from the 90s
    url: https://archive.org/details/1990-ngs-pdf/295EC01A.JPG
    desc: what the title says

- Link:
    title: Whole Earth Index
    url: https://wholeearth.info/
    desc: archive of the whole earth catalogue and others very interesting articles

- Link:
    title: Archive Fashion
    url: https://www.archivepdf.net/
    desc: i know nothing about high fashion but the magazines r cool

- Link:
    title: Standard EBooks
    url: https://standardebooks.org/
    desc: public domain ebooks very nicely formatted

- Link:
    title: METS
    url: https://metseditions.org/
    desc: middle english texts

- Link:
    title: bitsavers
    url: https://bitsavers.org/
    desc: archive of old software, manuals, magazines, and so on to do mostly with nonconsumer computing


#<-----MEDIA------>
- Media:
    tags: book
    title: The Woman in the Dunes
    author: Kōbō Abe
    thumbsup: true
    review: 🤔
    daterange: 25 - 26 Feb 2026
    slug: dunes
    richcontent: >
        enjoyed it. for some reason even though I find Kobo Abe's writing kinda offputting at times (intentionally) 
        i find it very quick to read. he seems to like to be very visceral. in this book less so than in The Ark Sakura 
        but all the same. always wonder whether the dialogue is so halting because of the translation or the actual writing itself.
        also the main characters in this and the ark sakura are very similar. both sorta odd and interested in bugs... makes you wonder.
        the whole metaphysical aspect interesting but not mind blowing or particularly emotive. more raises things to be considered than 
        immerses you in their consideration.
        
- Media:
    tags: book,fave
    title: Tess of the D'Urbervilles
    author: Thomas Hardy
    thumbsup: true
    review: 🤯
    slug: tess
    richcontent: >
        one of my favourite books ever. could talk adn talk about it but probs without saying much...
        the entirety of the book is full of a hazy overexposed glowing atmosphere which i am yet to find elsewhere,
        and the actual plot itself..

- Media:
    tags: book,fave
    title: Catch 22
    author: Joseph Heller
    thumbsup: true
    review: 🤩
    slug: catch22
    richcontent: >
        my other favourite book. similar to tess could talk a lot about it but unlike tess i think i could actually say something.
        very funny. funnier than any other book i've read and any movie or tv show or anything. and then all of a sudden the humour 
        drops away and your left alone in the night in rome or in the back of a bomber or with major major major major on the basketball
        court. poor major major major major

- Media:
    tags: series,fave
    title: Buffy the Vampire Slayer
    author: Sarah Michelle Gellar
    thumbsup: true
    review: 🧛
    slug: buffy
    richcontent: >
        easily the best tv show. or maybe not easily but pretty easily. some people think the title sounds dumb and some people think the synopsis sounds 
        dumb but the whole show just works


- Media:
    tags: series,fave
    title: Twin Peaks
    author: David Lynch
    thumbsup: true
    review: 🗻
    slug: twinpeaks
    richcontent: >
        i doubt i really have much to add. i love major garland briggs. 

- Media:
    tags: book,fave
    title: Of Human Bondage
    author: W. Somerset Maugham
    thumbsup: true
    review: 🧥
    slug: ofhumanbondage
    richcontent: >
        a character in buffy said this was their comfort book and idk if it quite is for me but it could be. i get it. something about it you could 
        just sink into and curl up.

- Media:
    tags: book,fave
    title: Moby Dick
    author: Herman Melville
    thumbsup: true
    review: 🐳
    slug: mobydick
    richcontent: >
        i LOVE moby dick. easily up there. i love ishmael. i love queequeg. i love that one scene in the spouter inn when they curl up and ishmael says 
        that he feels like "the one warm spark in the heart of an arctic crystal" and thats how i feel and think whenever its cold. i love how herman decides
        that half way through his book would be a good time to explain his new whale theory. i like his whale theory. i was expecting a dense tome and 
        it's def a tome but its so beautifully written and airy and aeried 

- Media:
    tags: film,fave
    title: Sherlock Jr.
    author: Buster Keaton
    thumbsup: true
    review: 💘
    slug: sherlockjr
    richcontent: >
        i love buster keaton. i occasionally think of buster keaton and just start smiling. have you seen his face when he just stands there. he has that look on his face.
        theres a scene in this movie where he's captaining a car on a river. i wish i were buster keaton. i saw this movie first with a live score
        which i think added a lot. silent films were never rlly meant to be silent yk.

- Media:
    tags: film,fave
    title: Nowhere
    author: Gregg Araki
    thumbsup: true
    review: 👽
    slug: nowhere
    richcontent: >
        for some reason i rlly love this movie. i didnt think i would as much as i did. its kinda stupid but it just worked for me. i love all the rooms
        and all the dialogue and the whole vibe. im outta here...

- Media:
    tags: music,fave
    title: Blaze Down His Way Like the Space Show
    author: Burrrn
    thumbsup: true
    review: 🛰️
    slug: burrrn
    richcontent: >
        i particularly like coming place and shut my eyes and picture story show and song without words. if you like shoegaze... have a unique sound 
        i would argue especially evident on coming place. 

- Media:
    tags: music,fave
    title: Live Nassau Coliseum &#39;76
    author: David Bowie
    thumbsup: true
    review: 🧑‍🎤
    slug: nassau
    richcontent: >
        david bowie is my favourite musician ever and this is his best live album ever. arguably his best album ever only in as much as it has so many songs
        from so many of his best albums yk. the version of five years in particular is great. all the cocaine he was doing some how made his voice
        more emotional i think. i think i saw you in a ice cream parlour drinking milk shakes cold and long. smiling and waving and looking so fine. dont think you knew you were in my song. adn it was cold and it rained and i felt like an actor
        
- Media:
    tags: music,fave
    title: MELTING MOMENT
    author: POiSON GiRL FRiEND
    thumbsup: true
    review: 🌆
    slug: meltingmoment
    richcontent: >
        FACT 2 is very good. MELTING MOMENT (the song) is very good. makes me feel like cars driving past at night with headlights on. i 
        saw her live in warsaw and she played falling by julie cruise.... how is she so cool.
